spring.application.name=api
server.port=8080

spring.mongodb.uri=mongodb://oleksandrhelevan:1234qwer_2006@admission-shard-00-00.n8xqw.mongodb.net:27017,admission-shard-00-01.n8xqw.mongodb.net:27017,admission-shard-00-02.n8xqw.mongodb.net:27017/note_app?ssl=true&replicaSet=atlas-vdbz3r-shard-0&authSource=admin&appName=admission